### ISSUE TITLE
Process and train very fast but got bad effect

### ISSUE THREAD

**Issue by AaronWaxson** [Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting#1] opened 2023-02-16 13:34 UTC
Hello, thanks for sharing work first!
I encountered some troubles when I wanted to reproduce the repo, here's the time consuming of each step:
1. script_vectorize_hd_maps: about 2100 seconds
2. script_transform_to_polylines: about 47 seconds
3. script_train_vectornet: about 5 seconds with RTX3090/20 seconds with cpu

And result shows that:
`Epoch 49: 100%|█| 30/30 [00:05<00:00,  5.02it/s, loss=68.8, v_num=0, val/loss=70.60, val/tg_confidence_loss=473.0, val/tg_huber_loss=24.90, val/tf_huber_loss=8.820, val/tf_confidence_loss=120.0, e2e/min_ad`

I used the `src/configs/vectornet.yaml` configuration.
Is there any mistakes I made?

**Comment by Robotmurlock** [comment] 2023-02-16 16:23
Hey, thanks for the feedback :)

Can you send me script logs? I am mostly interested in first one. Maybe most of the samples were removed by filter? I see that there are only 30 batches that data loader sees during training but is should be a lot higher.

Data structure should be like this:
```
{config.global_path}/
   dataset/
     train/*
        ... csv files
     val/*
     test/*
```

When you run first and second script then `internal` and `internal_graph` with `train/val/test` will appear in the global directory. I'm sending you dataset sample which you can use to test. Just drop it in global path you defined and test it.

[sample100.zip](https://github.com/Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting/files/10758145/sample100.zip)

**Comment by AaronWaxson** [comment] 2023-02-17 02:11
Ok, I'll test it.
And here's the result I got yesterday with full argoverse dataset:
![image](https://user-images.githubusercontent.com/37990023/219531150-8350c962-4862-44a0-a83f-12af0bc364d7.png)
![image](https://user-images.githubusercontent.com/37990023/219531419-c4f6f217-8760-494c-9302-a65eb2297cc3.png)
I noticed the file number and storage decreasing huge after script_transform_to_polylines, may help figure out the probolem

**Comment by AaronWaxson** [comment] 2023-02-17 02:22
And here's the log generated by script_vectorize_hd_maps with the sample100.zip
[test.log](https://github.com/Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting/files/10762634/test.log)

**Comment by Robotmurlock** [comment] 2023-02-17 08:09
Logs are okay. Seems like `script_vectorize_hd_maps` is working properly. Can you run full pipeline for sample and check if you lose some files? For `sample100` in `internal/train` and `internal_graph/train` you should have 100 directories (just tested it). If you get less than 100 samples in `internal_graph/train` please send me the logs.

For full dataset both `internal/train` and `internal_graph/train` should have 205706 items. Also `script_transform_to_polylines` generates around 60GB of data (without visualizations).

**Comment by AaronWaxson** [comment] 2023-02-17 12:45
I run the script_transform_to_polylines with `sample100` and got 100 samples.
Then I run it with full dataset only get: `test: 280, train:2818, val:438`, you can check this log file: [test.log](https://github.com/Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting/files/10766800/log.log)

**Comment by Robotmurlock** [comment] 2023-02-17 17:24
I am not able to reproduce the bug (I get everything generated). I see that you now have different number of files than last time. Try using only one process (n_processes = 1). That will run the program sequentially.

**Comment by AaronWaxson** [comment] 2023-02-18 09:27
I use one process to run the scripts again, got the `internal` and `internal_graph` with right size/num.
Seems multiprocessing has some problem...
I'm training, if get any problem, I'll give feedback again, thanks for your help~

**Comment by THN0000** [comment] 2023-02-24 16:01
> I am not able to reproduce the bug (I get everything generated). I see that you now have different number of files than last time. Try using only one process (n_processes = 1). That will run the program sequentially.

I use one process and get the right result. I also found that if you set n_processes >= 1, you will be spend more than 10 hours. 
And anybody knows why I always get the "Error: "Trajectory length threshold is 25 but found length is 20!"" while I was runing the "/common_data_processing/script_vectorize_hd_maps.py"? 
Thanks for your help.

**Comment by Robotmurlock** [comment] 2023-02-24 17:25
Hey @THN0000. I disabled multiprocessing for polylines script. I will add it again if duration of that script becomes a problem. 

Minimum trajectory length is equal to: `trajectory_history_window_length` + `trajectory_min_history_window_length` which is should be equal to `30` and `5` respectively by default in configs. You can update those parameters in config but for Argoverse benchmark it is convention to use `trajectory_min_history_window_length=30`.

**Comment by THN0000** [comment] 2023-02-24 17:25
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Robotmurlock** [comment] 2023-02-28 07:32
Closing it as the main issue is resolved. Multiprocessing for polylines is disabled for now.

**Closed as completed by Robotmurlock** 2023-02-28 07:32 UTC
